name: ABBYY Automation

on:
  schedule:
    - cron: "0 13 * * *" # 8am Hora Colombia (UTC -5)
  workflow_dispatch:

jobs:
  envio-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from repository secrets
        run: |
          echo "ABBYLINK=${{ secrets.ABBYYLINK }}" >> .env
          echo "ABBYUSERNAME=${{secrets.ABBYUSERNAME}}" >> .env
          echo "ABBYPASSWORD=${{secrets.ABBYPASSWORD}}" >> .env
          echo "EMAIL_TO=${{secrets.EMAIL_TO}}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo ".env file created successfully"

      - name: Validate .env file
        run: |
          if [ ! -f .env ]; then
            echo "Error: .env file not created!"
            exit 1
          else
            echo ".env file content:"
            cat .env
          fi

      - name: Config Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate Node and npm
        run: node -v && npm -v

      - name: Install dependencies
        run: npm install

      - name: Install Browsers
        run: npx playwright install

      - name: Start Development
        run: npm run start
